prgrms-web-devcourse-final-project/WEB_3_4_SsamMuDan_FE

src/common/Badge.jsx, src/common/StackBadge.jsx, src/pages/Jiwoo.jsx
(#11 ) jiwoo -> main
- 일반 뱃지 컴포넌트 추가
=> Feat #11 : 일반 뱃지 컴포넌트 작업

index.html, public/images/main-footer-logo.svg, src/common/Layout/Footer.jsx, src/common/Layout/Header.jsx, src/index.css, tailwind.config.js
ex) (#8) jonghee -> main
footer 디자인 개발
=> Feat #8 : footer 작업

src/components/common/PositionModal.jsx, src/components/common/PrimaryButton.jsx, src/components/common/StackModal.jsx
=> docs: 파일명 변경

src/components/common/LectureCardSimple.jsx, src/pages/Jiwoo.jsx, tailwind.config.js
(#22) jiwoo -> main
- (마이페이지, 교육 배너용) 강의 카드 컴포넌트 추가
=> Feat #22 : (마이페이지, 교육 배너용) 강의 카드 컴포넌트 작업

src/components/common/CustomPagination.jsx, src/components/common/PositionModal.jsx, src/components/common/StackModal.jsx, src/components/ui/pagination.jsx, src/pages/Jungseok.jsx
ex) (#21 ) jungseok -> main
페이지네이션 기능 추가
=> feat #21: 페이지네이션 작업

src/components/common/IntroduceInput.jsx, src/components/common/IntroduceTextArea.jsx, src/components/ui/textarea.jsx, src/pages/Jungseok.jsx
=> feat #25 : introduceInput, introduceTextArea 컴포넌트 작성

package-lock.json, src/App.jsx, src/components/common/PrimarySelect.jsx, src/components/ui/select.jsx, src/index.css, src/pages/JongHee.jsx
ex) (#27)jonghee -> main
select 작업 완료
=> Feat #27 : select 박스

public/images/AddButton.svg, src/components/common/AddButton.jsx, src/pages/Jungseok.jsx
(#30) jungseok -> main
추가 버튼 컴포넌트 작업 완료
=> design #30 : 추가 버튼 컴포넌트 작업

package-lock.json, package.json, src/components/common/CategorySlider.jsx, src/components/common/CategoryTab.jsx, src/pages/Jungseok.jsx
ex) (#33 ) jungseok -> main
카테고리 탭 전화 컴포넌트 작업했습니다
=> 카테코리 탭 컴포넌트 작성 

package-lock.json, package.json, src/App.jsx, src/components/careerDetail/CareerDetailSection.jsx, src/components/careerDetail/Comment.jsx, src/components/careerDetail/CommentSection.jsx, src/components/careerDetail/IntroduceProjectForm.jsx, src/components/careerDetail/IntroduceSection.jsx, src/components/careerDetail/ProjectDetailSection.jsx, src/components/common/CustomPagination.jsx, src/components/common/IntroduceBar.jsx, src/components/ui/avatar.jsx, src/pages/CareerDetail.jsx
=> design #45 : 이력서 상세페이지 디자인 작업

package-lock.json
=> react pdf, react viewer 설치

src/components/careerWrite/CareerForm.jsx, src/components/careerWrite/DateSetForm.jsx, src/components/careerWrite/ProjectContentForm.jsx, src/components/careerWrite/ProjectForm.jsx, src/pages/CareerWrite.jsx
ex) (#50 ) jungseok -> main
채용정보 작성 페이지 퍼블리싱 작업
=> design #50 : 채용정보 작성 페이지 완료

src/components/educationDetail/EducationBookDetailIntro.jsx
=> feat : pdf 미리보기 기능

src/App.jsx, src/pages/CommunityWrite.jsx
(#71) jiwoo -> main
- 커뮤니티 작성페이지 퍼블리싱
=> design #71 : 커뮤니티 작성페이지 퍼블리싱

src/components/career/HistoryModal.jsx, src/components/common/PositionModal.jsx, src/components/common/StackModal.jsx
=> design #76 : 모달 스타일 수정

src/components/careerDetail/IntroduceSection.jsx
=> design #81 : 채용 상세페이지 스타일 수정

src/components/career/HistoryModal.jsx, src/components/common/PositionModal.jsx, src/components/common/StackModal.jsx, src/components/projectJoin/HeroSection.jsx, src/components/projectJoin/HotProjectCard.jsx, src/components/projectJoin/ProjectCard.jsx
ex) (#85 ) jungseok -> main
프로젝트 조회 페이지 스타일 수정
=> design #85 : 프로젝트 조회 페이지 스타일 수정

src/components/common/IntroduceInput.jsx, src/components/common/IntroduceTextArea.jsx, src/components/projectJoinWrite/ProjectInfoForm.jsx, src/components/projectJoinWrite/ProjectPeriod.jsx, src/components/ui/input.jsx
ex) (#89 ) jungseok -> main 
프로젝트 작성 페이지 스타일 수정
=> design #89 : 프로젝트 작성 페이지 스타일 수정

package-lock.json, package.json, src/api/career/getCareerInfo.js, src/api/endpoint.js, src/config/career.js, src/pages/Career.jsx
=> feat : api endPoint 정리

src/api/career/getCareerInfo.js, src/api/endpoint.js, src/components/career/HeroRight.jsx, src/components/common/PositionModal.jsx, src/components/common/StackModal.jsx, src/config/cotree.js, src/pages/Career.jsx
=> 채용 조회 중간 작업

package-lock.json, package.json, src/api/career/getCareerInfo.js, src/api/endpoint.js, src/api/main/getCommunityPosts.js, src/components/main/CommunityCard.jsx, src/components/main/CommunitySection.jsx, src/components/main/SlideButton.jsx, src/pages/Community.jsx
(#99) jiwoo -> main
- 커뮤니티 게시글 조회 엔드포인트 & API 함수 추가(getCommunityPosts)
- Swiper 패키지 추가
- 메인페이지에 커뮤니티 게시글 조회 API 연동 & 스와이퍼 구현
- 커뮤니티 카드 UI 약간 수정
=> feat #99 : 메인페이지에 커뮤니티 게시글 조회 API 연동 & 스와이퍼 구현

package-lock.json, package.json, src/App.jsx, src/api/careerWrite/getSkillStack.js, src/common/StackBadge.jsx, src/components/career/HistoryModal.jsx, src/components/careerWrite/BasicForm.jsx, src/components/careerWrite/CareerContentForm.jsx, src/components/careerWrite/CareerForm.jsx, src/components/careerWrite/DateSetForm.jsx, src/components/common/IntroduceInput.jsx, src/components/common/IntroduceTextArea.jsx, src/components/common/PositionModal.jsx, src/pages/Career.jsx, src/pages/CareerWrite.jsx, src/store/careerWriteStore.js
=> feat : 채용작성페이지 중간 작업

src/pages/Education.jsx, src/store/TechBookSearch.jsx
ex) (#103) jonghee -> main
교육페이지 만들다가 에러가 나서 수정하고 올립니다
=> fix#103:교육페이지 수정

src/api/education/getTechBookDetail.js, src/components/main/TechBookBest.jsx, src/components/main/TechBookList.jsx, src/components/main/TechBookSection.jsx
(#107) jiwoo -> main
- 테크북 상세페이지 조회 API 함수 추가(getTechBookDetail)
- 메인페이지에 테크북 조회 API 연동 (카테고리는 아직!)
- 메인페이지 테크북 카드 썸네일이미지에 임시 border 추가 -> 이미지 보이면 제거할 예정
=> feat #107 : 메인페이지에 TechBook 조회 API 연동

src/api/endpoint.js, src/api/login/loginUser.js, src/components/login/LoginFormContainer.jsx, src/components/main/TechBookBest.jsx, src/components/main/TechBookList.jsx, src/store/useAuthStore.js
(#110) jiwoo -> main
- 일반 로그인 기능 구현
- 로그인 엔드포인트, API 함수 추가(loginUser)
- 기타: 메인페이지 테크북 강의카드 border 제거
=> feat #110 : 일반 로그인 기능 구현

src/api/endpoint.js, src/api/main/getProjectPostsMain.js, src/components/main/JoinCard.jsx, src/components/main/ProjectSection.jsx
(#109) jiwoo -> main
- 메인페이지에서 프로젝트 모집글 조회하는 엔드포인트 및 API 함수(getProjectPostsMain) 추가
- 메인페이지에 프로젝트 조회 API 연동
(‼️ 프로젝트 카드에 '#프론트엔드 #백엔드' 등의 태그 대신 기술 스택 아이콘으로 변경)
=> feat #109 : 메인페이지에 프로젝트 조회 API 연동

src/api/careerWrite/postRecruitment.js, src/api/endpoint.js, src/api/login/loginUser.js, src/components/careerWrite/BasicForm.jsx, src/components/careerWrite/CareerContentForm.jsx, src/components/careerWrite/CareerForm.jsx, src/components/careerWrite/DateSetForm.jsx, src/components/careerWrite/ProjectContentForm.jsx, src/components/careerWrite/ProjectForm.jsx, src/components/common/AddButton.jsx, src/components/common/IntroduceInput.jsx, src/components/common/IntroduceTextArea.jsx, src/components/common/ThemeToggle.jsx, src/config/cotree.js, src/pages/CareerWrite.jsx
#116  jungseok -> main
채용지원 작성페이지 기능 완료
=> feat #116 : 채용지원 작성 기능

src/components/common/CustomPagination.jsx, src/pages/Education.jsx
ex) (#103) jonghee -> main
1.페이지네이션 변경
=> fix#103:교육페이지 조회 수정

src/api/endpoint.js, src/api/login/getUserInfo.js, src/api/login/logoutUser.js, src/api/signup/postSignup.js, src/common/Layout/Header.jsx, src/components/login/LoginFormContainer.jsx, src/components/main/JoinCard.jsx, src/components/signup/SignupFormContainer.jsx, src/store/useAuthStore.js
(#113) jiwoo -> main
- 회원가입 기능 구현(이메일, 휴대폰 인증은 아직 미완성)
- 회원가입, 로그인한 사용자의 정보 조회, 로그아웃 엔드포인트 및 API 함수 추가
- 로그인 정보 스토어 추가(useAuthStore)
- 메인페이지의 프로젝트 카드 기술스택 아이콘 사이즈 수정
=> feat #113 : 회원가입 기능 (이메일, 휴대폰 인증 미완성)

src/api/endpoint.js, src/api/techbookDetail/techbookDetail.js, src/components/educationDetail/EducationBookDetailIntro.jsx, src/components/educationDetail/EducationDetailBookBanner.jsx, src/components/educationDetail/EducationDetailBookContent.jsx, src/components/educationDetail/EducationPay.jsx, src/components/ui/skeleton.jsx, src/pages/Education.jsx, src/pages/TechBook.jsx
=> fix#114:교육상세 페이지

netlify.toml, src/api/careerDetail/getPosition.js, src/api/endpoint.js, src/components/careerWrite/BasicForm.jsx
=> feat : 직무 조회 및 netlify 배포 연동

src/App.jsx, src/api/endpoint.js, src/api/signup/postSignupEmail.js, src/api/signup/postSignupEmailVerify.js, src/api/signup/postSignupPhone.js, src/api/signup/postSignupPhoneVerify.js, src/components/login/LoginFormContainer.jsx, src/components/signup/SignupFormContainer.jsx, src/pages/LoginKakaoCallback.jsx
(#113, #125) jiwoo -> main
- 회원가입 휴대폰번호 및 이메일 인증 관련 엔드포인트, API 함수 추가
- 회원가입 휴대폰번호 및 이메일 인증 구현
- 카카오 로그인 연동
‼️ 일반 회원가입한 이메일 계정으로만 카카오 로그인 가능
=> feat #113, #125 : 회원가입 휴대폰번호 및 이메일 인증, 카카오 로그인

src/api/career/getCareerInfo.js, src/api/careerDetail/getPosition.js, src/api/endpoint.js, src/components/career/CardList.jsx, src/components/career/HeroRight.jsx, src/components/career/HistoryModal.jsx, src/components/career/ProfileCard.jsx, src/components/careerDetail/CareerDetailSection.jsx, src/components/careerWrite/BasicForm.jsx, src/components/careerWrite/CareerContentForm.jsx, src/components/common/PositionModal.jsx, src/components/common/PrimarySelect.jsx, src/components/common/StackModal.jsx, src/pages/Career.jsx
- 좋아요 정렬 빼고 다 완료
ex) (#95 ) feat/login -> dev
좋아요 정렬 제외하고 모든 기능 완료
=> feat # 95 : 채용 지원 페이지 기능

src/api/projectJoin/getPosition.js, src/api/projectJoin/getProjectList.js, src/components/common/PrimarySelect.jsx, src/components/projectJoin/ProjectCard.jsx, src/components/projectJoin/projectPositionModal.jsx, src/pages/ProjectJoin.jsx
=> feat #120 : 프로젝트 조회 중간 작업

src/api/projectJoin/getProjectList.js, src/components/projectJoin/HotProjectCard.jsx, src/pages/ProjectJoin.jsx
=> feat #120 : 채용 조회 페이지 완료

src/App.jsx, src/api/endpoint.js, src/api/projectJoinWrite/postProject.js, src/components/career/HeroRight.jsx, src/components/careerWrite/BasicForm.jsx, src/components/projectJoin/HeroSection.jsx, src/components/projectJoin/ProjectCard.jsx, src/components/projectJoinWrite/PositionSetting.jsx, src/components/projectJoinWrite/ProjectInfoForm.jsx, src/components/projectJoinWrite/ProjectPeriod.jsx, src/pages/CareerWrite.jsx
ex) (#145 ) jungseok-> main
프로젝트 작성 페이지 기능
=> feat #145 : 프로젝트 작성 페이지 기능 완성

src/components/projectJoin/ProjectCard.jsx, src/components/projectJoinWrite/ProjectInfoForm.jsx, src/pages/Career.jsx, src/pages/ProjectJoin.jsx
=> fix : 연락처 type String 변환

src/api/endpoint.js, src/components/careerDetail/CommentSection.jsx, src/components/projectJoinWrite/ProjectInfoForm.jsx
=> feat : 이메일 검증 기능

src/api/mypage/editUserInfo.js, src/api/mypage/uploadProfileImage.js, src/common/Layout/Header.jsx, src/components/mypage/EditProfileModal.jsx, src/components/mypage/MypageInfo.jsx
(#138, #150) jiwoo -> main
- 회원정보 변경 및 프로필 이미지 업로드 API 함수 추가
- 마이페이지에 회원정보 변경 기능 추가 (‼️ 프로필 이미지는 아직 미완성 -> 이름, 닉네임만 변경 가능)
- 헤더에 로그인 사용자 정보 표시 기능 추가
=> feat #138, #150 : 회원정보 변경 기능 및 헤더에 로그인 사용자 표시 기능

src/components/careerDetail/ProjectDetailSection.jsx, src/pages/CareerDetail.jsx, src/pages/Community.jsx, src/pages/JongHee.jsx
fork/repo/dev -> origin/repo/dev
import 대소문자 구분
=> [FIX]: import UpperCase

src/api/endpoint.js, src/api/techtubeDetail/postTechTubePay.js, src/components/educationDetail/EducationDetailBanner.jsx, src/components/educationDetail/EducationPay.jsx, src/pages/Community.jsx, src/pages/CommunityWrite.jsx, src/pages/TechTube.jsx
=> feat #160: 테크튜브 관련 작업

src/api/careerDetail/getComment.js, src/api/careerDetail/postComment.js, src/components/careerDetail/Comment.jsx, src/components/careerDetail/CommentSection.jsx, src/components/careerDetail/ReplyComment.jsx, src/components/common/CustomPagination.jsx, src/pages/CareerDetail.jsx
=> feat #119 : 프로젝트 조회 페이지 완료

src/api/careerDetail/getComment.js, src/components/careerDetail/Comment.jsx, src/components/careerDetail/CommentSection.jsx, src/components/careerDetail/ReplyComment.jsx, src/pages/CareerDetail.jsx, src/pages/CommunityDetail.jsx
- N분 전
- N시간 전
- N일 전
ex) (#119) jungseok -> main
=> fix #119 : 댓글 등록 시간 표현 변경

src/components/mypage/MyProjectCard.jsx, src/components/projectJoin/StackIcon.jsx, src/pages/Jungseok.jsx
=> feat: 마이페이지 프로젝트 카드 디자인

src/api/signup/postSignup.js, src/components/signup/SignupFormContainer.jsx
=> fix : 회원가입 API 함수 수정

src/api/endpoint.js, src/api/main/getProjectPostsMain.js, src/api/main/getTechbookMain.js, src/api/main/getTechtubeMain.js, src/api/mypage/getOrderList.js, src/common/Layout/Header.jsx, src/components/common/LectureCardSimple.jsx, src/components/common/LottieEmpty.jsx, src/components/main/CareerSection.jsx, src/components/main/CommunitySection.jsx, src/components/main/ProjectSection.jsx, src/components/main/TechBookBest.jsx, src/components/main/TechBookList.jsx, src/components/main/TechBookSection.jsx, src/components/mypage/MypageInfo.jsx, src/components/mypage/MypageTabs.jsx
(#137, #163) jiwoo -> main
- 회원 구매목록 조회 엔드포인트 추가 및 메인페이지 프로젝트 조회 엔드포인트 수정
- 회원 구매목록 조회 및 메인페이지 테크북 조회 API 함수 추가
- 마이페이지 회원 구매목록 조회 기능 (데이터 없을 때 로티 애니메이션 추가)
- 메인페이지 Techbook 교육 카테고리와 연결
- 기타: 헤더 사용자 프로필 눌렀을 때 드롭박스 위치 수정, 메인페이지의 각 타이틀 문구 약간 수정함
=> feat #137, #163 : 메인페이지에 TechBook 교육 카테고리와 연결 및 마이페이지 구매 목록 조회 기능

src/api/career/getCareerInfo.js, src/api/projectJoin/getProjectList.js, src/components/career/DateSelect.jsx, src/components/careerDetail/ReplyComment.jsx, src/components/common/PrimarySelect.jsx, src/components/projectJoinWrite/ProjectInfoForm.jsx, src/pages/Career.jsx, src/pages/ProjectJoin.jsx
- 프로젝트 생성시 postData에 endDate 포함
- 채용 조회, 프로젝트 조회에서 정렬 컴포넌트 생성 및 로직 재구성
- 대댓글 예외처리
=> hoxfix : 에러 해결

src/components/login/LoginFormContainer.jsx, src/components/signup/SignupFormContainer.jsx
=> fix : alert -> toast 처리

vercel.json
=> fix : Vercel 새로 고침 404 에러

src/App.jsx, src/components/career/HeroLeft.jsx, src/components/career/HeroRight.jsx, src/components/career/ProfileAd.jsx, src/components/signup/SignupFormContainer.jsx, src/pages/SignupSuccess.jsx
jiwoo -> main
- 회원가입폼 이메일 및 휴대폰번호 인증에 3분 타이머 추가
- 회원가입 완료페이지 추가
- 기타: 채용 조회페이지 히어로 텍스트 수정
=> feat : 회원가입폼 이메일 및 휴대폰번호 인증에 3분 타이머 추가, 회원가입 완료페이지 추가

src/api/endpoint.js, src/api/login/postFindIdCode.js, src/api/login/postFindIdCodeVerify.js, src/components/login/FindIdModal.jsx, src/components/login/LoginFormContainer.jsx
(#180) jiwoo -> main
- 아이디찾기 휴대폰번호 인증코드 전송 및 확인 관련 엔드포인트, API 함수 추가
- 아이디찾기 기능 추가
=> feat #180 : 로그인 아이디찾기 기능 추가

src/api/community/postCreateCommunity.js, src/components/ProjectDetail/PositionSection.jsx, src/components/community/CommunityBestSection.jsx, src/components/community/CommunityList.jsx, src/components/main/CommunityCard.jsx, src/components/main/CommunitySection.jsx, src/components/main/JoinCard.jsx, src/components/main/TechBookBest.jsx, src/components/main/TechBookList.jsx, src/components/main/TechTubeList.jsx, src/pages/Community.jsx, src/pages/CommunityWrite.jsx, src/pages/Main.jsx, src/pages/TechBook.jsx, src/pages/TechTube.jsx
(#183) jiwoo -> main
- 프로젝트 상세페이지에서 작성자만 보여야 되는 문구 수정
- 메인페이지의 각 데이터 해당 상세페이지로 이동
- 커뮤니티 게시글 작성 및 수정 시 해당 게시글의 상세페이지로 이동
- 커뮤니티 조회페이지에서 프로필사진 없을 때 기본 이미지 추가
=> fix #183 : 프로젝트 상세페이지에서 작성자만 보여야 되는 문구 수정 및 기타 수정 (변경 사항 내용 참고!)

src/api/community/deleteCommunityLike.js, src/api/community/getLikedCommunity.js, src/api/community/postCommunityLike.js, src/api/endpoint.js, src/components/communityDetail/CommunityFloating.jsx, src/components/login/LoginFormContainer.jsx, src/components/mypage/MypageTabs.jsx, src/components/mypage/MypageToggle.jsx, src/pages/CommunityDetail.jsx, src/pages/Mypage.jsx
(#192) jiwoo -> main
- 내가 좋아요한 커뮤니티 게시글 조회 엔드포인트 추가
- 커뮤니티 게시글 좋아요 등록 및 삭제, 내가 좋아요한 게시글 조회 API 함수 추가
- 커뮤니티 게시글 좋아요 등록 및 삭제 기능 추가 후 마이페이지 관심목록에 연동
=> feat #192 : 커뮤니티 게시글 좋아요 기능 추가 후 마이페이지 관심목록에 연동

src/api/endpoint.js, src/api/projectJoin/deleteProjectLike.js, src/api/projectJoin/getLikedProject.js, src/api/projectJoin/postProjectLike.js, src/components/ProjectDetail/ProjectFloating.jsx, src/pages/ProjectJoinDetail.jsx
(#194) jiwoo -> main
- 내가 좋아요한 프로젝트 모집글 조회 엔드포인트 추가
- 프로젝트 모집글 좋아요 등록 및 삭제, 내가 좋아요한 글 조회 API 함수 추가
- 프로젝트 모집글 좋아요 등록 및 삭제 기능 추가 (‼️ 마이페이지 연동은 아직 미완성)
=> feat #194 : 프로젝트 모집글 좋아요 등록 및 삭제 기능 (마이페이지 연동은 아직 미완성)

src/components/ProjectDetail/FindPeople.jsx, src/components/ProjectDetail/PositionSection.jsx, src/components/projectJoin/ProjectCard.jsx, src/pages/Career.jsx, src/pages/ProjectJoin.jsx
jiwoo -> main
- 채용, 프로젝트 조회페이지에서 페이지네이션 초기화되는 문제 수정
- 프로젝트 상세페이지 안내 문구 변경 및 UI 약간 수정
=> fix : 채용, 프로젝트 조회페이지에서 페이지네이션 초기화되는 문제 수정

src/components/mypage/MyProjectCard.jsx, src/components/mypage/MypageTabs.jsx
(#194) jiwoo -> main
- 내가 좋아요한 프로젝트 모집글 마이페이지 관심목록에 추가
=> feat #194 : 내가 좋아요한 프로젝트 모집글 마이페이지에 연동

src/components/ProjectDetail/ProjectFloating.jsx, src/components/ProjectDetail/ProjectIntroduce.jsx, src/components/communityDetail/CommunityDetailInfo.jsx, src/components/communityDetail/CommunityFloating.jsx, src/pages/CommunityDetail.jsx, src/pages/CommunityWrite.jsx, src/pages/Payment.jsx, src/pages/ProjectJoinDetail.jsx
ex) (#203 ) jonghee-> main
1.플로팅 배치완료
=> feat #203: 플로팅 작업

src/api/endpoint.js, src/api/login/patchResetPassword.js, src/api/signup/postSignupEmail.js, src/api/signup/postSignupEmailVerify.js, src/components/login/LoginFormContainer.jsx, src/components/login/ResetPasswordModal.jsx, src/components/main/TechBookBest.jsx, src/components/main/TechBookList.jsx, src/components/main/TechBookSection.jsx, src/components/main/TechTubeSection.jsx, src/components/mypage/EditProfileModal.jsx, src/components/mypage/MypageTabs.jsx
(#181) jiwoo -> main
- 비밀번호 재설정 관련 엔드포인트 및 API 함수 추가
- 비밀번호 재설정 기능 추가
- 메인페이지의 테크 섹션에 로딩중 컴포넌트 추가
- 마이페이지 회원정보 변경 후 나오는 toast를 다시 alert으로 수정
- 마이페이지 관심목록의 테크튜브, 테크북 썸네일 이미지 경로 수정
=> feat #181 : 비밀번호 재설정 기능 및 기타 수정

src/components/educationDetail/EducationPay.jsx
ex) (#206 )jonghee -> main
결제변경
=> fix#206 : 결제

src/pages/CareerDetail.jsx, src/pages/CareerWrite.jsx, src/store/useAuthStore.js
=> fix:채용 작성시 유저 네임 적용

src/components/mypage/MypageTabs.jsx
jiwoo -> main
- 마이페이지 구매목록 리스트 에러 수정
=> fix : 마이페이지 구매목록 리스트 에러 수정
